---
version: '3.2'
services:
  server:
    build:
      context: .
    environment:
      ENV: DEV
      PORT: 8000
    ports:
      - "8000:8000"
      - "9229:9229"
    volumes:
      - .:/usr/src/app
    command: ["npm", "run", "debug-docker"]
